# Generated by Django 2.1.7 on 2019-03-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='store.Tag'),
        ),
    ]
