# Generated by Django 2.1.7 on 2019-03-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190306_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='takes_two_columns',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
