# Generated by Django 2.1.7 on 2019-04-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_game_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
